# Generated by Django 5.0.4 on 2024-04-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('music', 'Music')], max_length=30, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Info')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('customer_name', models.CharField(max_length=60, verbose_name='Customer Name')),
                ('customer_position', models.CharField(max_length=60, verbose_name='Customer Position')),
                ('customer_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='OurInstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_link', models.URLField(verbose_name='Story link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=120, verbose_name='Title')),
                ('home_subtitle', models.CharField(max_length=120, verbose_name='subtitle')),
                ('home_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
        ),
    ]
