# Generated by Django 5.0.4 on 2024-05-02 00:58

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_ourinstagramstory_story_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='story_link',
            field=models.URLField(validators=[common.utils.check_instagram_url], verbose_name='Story link'),
        ),
    ]
