# Generated by Django 5.0.4 on 2024-04-29 01:38

import accounts.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,12}$')], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,12}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='verificationotp',
            name='code',
            field=models.IntegerField(validators=[accounts.utils.check_otp_code], verbose_name='Otp code'),
        ),
    ]
